name: Bloodstrike Mod Menu Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Theos
      run: |
        brew install ldid
        rm -rf ~/theos
        export THEOS=~/theos
        git clone --recursive https://github.com/theos/theos.git $THEOS
        # Clonar SDKs directamente para evitar errores de tar/archivo
        rm -rf $THEOS/sdks
        git clone --depth 1 https://github.com/theos/sdks.git $THEOS/sdks

    - name: Build Dylib
      run: |
        export THEOS=~/theos
        cd panel
        make clean
        make
      env:
        THEOS: ~/theos

    - name: Upload Dylib
      uses: actions/upload-artifact@v4
      with:
        name: Bloodstrike_ModMenu_Dylib
        path: panel/*.dylib
